# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

author:
  name:           'Li0liQ'
  url:            https://github.com/Li0liQ

paginate:         5

# Custom vars
github:
  repo:           https://github.com/Li0liQ/li0liq.github.io